name: sockets2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter:
  flutter_svg: ^0.17.1
  flare_flutter: ^2.0.1
  http:
  provider: ^4.0.4
  shared_preferences: ^0.5.2
  jaguar_jwt: ^2.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/